Update Check_Freeze

diff --git a/.github/workflows/Check_Freeze b/.github/workflows/Check_Freeze
--- a/.github/workflows/Check_Freeze
+++ b/.github/workflows/Check_Freeze
@@ -3,7 +3,7 @@ name: Check_Freeze
 on:
   pull_request:
     branches:
-      - main  # Adjust to your protected branch
+      - dev  # Adjust to your protected branch
 
 jobs:
   check-status:
@@ -13,29 +13,23 @@ jobs:
       - name: Checkout code
         uses: actions/checkout@v2
 
-      - name: Read State
-        id: state
+      - name: Read Freeze State
+        id: freeze-state
         run: |
-          state=$(cat .github/state.json)
-          echo "State: $state"
-          echo "::set-output name=state::$state"
+          freeze=$(cat .github/freeze.json)
+          echo "Freeze State: $freeze"
+          echo "::set-output name=freeze::$freeze"
 
       - name: Check Freeze Status
         id: check-freeze-status
         run: |
-          state="$INPUT_STATE"  # Use the state obtained from the previous step
-          if [ "$state" = "true" ]; then
-            echo "Freeze is active (true), failing the workflow."
-            echo "::set-output name=status::failure"
+          freeze="$INPUT_FREEZE"  # Use the freeze state obtained from the previous step
+          if [ "$freeze" = "true" ]; then
+            echo "Freeze is active (true), the workflow will fail."
+            exit 1
           else
-            echo "Freeze is inactive (false), workflow succeeds."
-            echo "::set-output name=status::success"
+            echo "Freeze is inactive (false), the workflow will succeed."
           fi
         env:
-          INPUT_STATE: ${{ steps.state.outputs.state }}
+          INPUT_FREEZE: ${{ steps.freeze-state.outputs.freeze }}
 
-      - name: Set Workflow Status
-        id: set-workflow-status
-        run: echo "Workflow status: ${{ steps.check-freeze-status.outputs.status }}"
-        env:
-          WORKFLOW_STATUS: ${{ steps.check-freeze-status.outputs.status }}
